//! operator config から terraform の env 設定（`terraform.tfvars`）を決定論的に生成する（#380）。
//!
//! `cn-operator generate-tfvars` は operator-config.yaml を単一の入力元として、
//! `infra/terraform/envs/low-cost` 用の `terraform.tfvars` を出力する。これにより運営者は
//! 同じ config から docs / manifest と terraform の env 設定の両方を得られる。
//!
//! 重要な不変条件:
//! - secret は **値ではなく Secret Manager の secret ID** のみを出力する（payload は出さない）。
//! - blob cache の on/off は `features.blob_cache` を真実源にして導出する（deploy 側で重複させない）。
//! - 出力は wall-clock 非依存で、同じ config からは同じ tfvars が得られる（決定論）。

use std::fmt::Write as _;
use std::ops::RangeInclusive;

use anyhow::{Result, bail};

use crate::config::{DeployConfig, DeployProfile, ResolvedConfig};

/// 関係解析の実行間隔（分）の許容範囲。Terraform の変数検証と同じ値にする。
///
/// readiness は解析の成功を既定 7200 秒以内に要求する。boot / startup 再実行の直後は初回まで
/// 最大 16 分かかるため、解析と boot の所要時間に 14 分を残す（#1101）。
const RELATION_ANALYZE_INTERVAL_MINUTES_RANGE: RangeInclusive<u32> = 1..=90;

/// `deploy.relation_analyze_interval_minutes` が許容範囲内かを検証する。
pub(crate) fn validate_relation_analyze_interval(minutes: u32) -> Result<()> {
    let range = RELATION_ANALYZE_INTERVAL_MINUTES_RANGE;
    if !range.contains(&minutes) {
        bail!(
            "deploy.relation_analyze_interval_minutes は {}〜{} で指定してください（readiness が求める関係解析の成功記録 7200 秒以内を保つため）",
            range.start(),
            range.end()
        );
    }
    Ok(())
}

/// operator-config から `terraform.tfvars`（HCL 文字列）を生成する。
///
/// `deploy` セクションが未指定の場合や、tfvars 生成未対応の profile の場合は error にする。
pub fn generate_tfvars(config: &ResolvedConfig) -> Result<String> {
    let Some(deploy) = config.deploy() else {
        bail!(
            "deploy セクションが指定されていません。\n\
             terraform.tfvars を生成するには operator-config.yaml に deploy: を追加してください。"
        );
    };

    if deploy.profile != DeployProfile::LowCost {
        bail!(
            "deploy.profile `{}` の tfvars 生成は未対応です（拡張点）。\n\
             現在 generate-tfvars が対応するのは low-cost のみです。",
            deploy.profile.key()
        );
    }

    Ok(render_low_cost_tfvars(config, deploy))
}

/// HCL の文字列値をダブルクォートで安全に出力する。
fn hcl_string(value: &str) -> String {
    let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

/// HCL の文字列 list を決定論的に出力する（要素は trim 済みを想定）。
fn hcl_string_list(values: &[String]) -> String {
    let items = values
        .iter()
        .map(|value| hcl_string(value.trim()))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{items}]")
}

/// low-cost env 用の tfvars を決定論的に組み立てる。
fn render_low_cost_tfvars(config: &ResolvedConfig, deploy: &DeployConfig) -> String {
    let project_id = deploy.project_id.trim();
    let region = deploy.region.trim();
    let zone = deploy.zone.trim();
    let api_domain = config.api_domain().trim();
    let relay_domain = deploy.relay_domain.as_deref().map(str::trim).unwrap_or("");
    let acme_email = deploy.acme_email.trim();
    let admin_actor = deploy.admin_actor.as_str();
    let blob_cache_enabled = config.blob_cache_enabled();
    let dns_zone_name = deploy.dns_zone_name.as_deref().map(str::trim).unwrap_or("");
    let cn_user_api_image = deploy.cn_user_api_image.trim();
    let cn_iroh_relay_image = deploy.cn_iroh_relay_image.trim();
    let cn_cli_image = deploy.cn_cli_image.trim();
    let jwt_secret_id = deploy.jwt_secret_id.trim();
    let postgres_password_secret_id = deploy.postgres_password_secret_id.trim();
    let safety_signing_key_secret_id = config
        .raw
        .safety
        .as_ref()
        .and_then(|safety| safety.events.signing_key_secret_id.as_deref())
        .map(str::trim)
        .unwrap_or("");
    let machine_type = deploy.machine_type.trim();
    let blob_cache_path = deploy.blob_cache_path.trim();

    let mut out = String::new();
    let _ = writeln!(
        out,
        "# Generated by `cn-operator generate-tfvars` from operator-config.yaml. Do not edit by hand."
    );
    let _ = writeln!(
        out,
        "# Re-run generate-tfvars after changing operator-config.yaml. Secret VALUES are never"
    );
    let _ = writeln!(
        out,
        "# written here; only Secret Manager secret IDs. terraform.tfvars is gitignored."
    );
    let _ = writeln!(out);

    let _ = writeln!(out, "project_id = {}", hcl_string(project_id));
    let _ = writeln!(out, "region     = {}", hcl_string(region));
    let _ = writeln!(out, "zone       = {}", hcl_string(zone));
    let _ = writeln!(out);

    let _ = writeln!(out, "api_domain   = {}", hcl_string(api_domain));
    let _ = writeln!(out, "relay_domain = {}", hcl_string(relay_domain));
    let _ = writeln!(out, "acme_email   = {}", hcl_string(acme_email));
    let _ = writeln!(out, "admin_actor  = {}", hcl_string(admin_actor));
    let _ = writeln!(out);

    let _ = writeln!(out, "manage_cloud_dns = {}", deploy.manage_cloud_dns);
    let _ = writeln!(out, "dns_zone_name    = {}", hcl_string(dns_zone_name));
    let _ = writeln!(out);

    let _ = writeln!(
        out,
        "cn_user_api_image   = {}",
        hcl_string(cn_user_api_image)
    );
    let _ = writeln!(
        out,
        "cn_iroh_relay_image = {}",
        hcl_string(cn_iroh_relay_image)
    );
    let _ = writeln!(out, "cn_cli_image        = {}", hcl_string(cn_cli_image));
    let _ = writeln!(out);

    let _ = writeln!(
        out,
        "jwt_secret_id                = {}",
        hcl_string(jwt_secret_id)
    );
    let _ = writeln!(
        out,
        "postgres_password_secret_id  = {}",
        hcl_string(postgres_password_secret_id)
    );
    let _ = writeln!(
        out,
        "safety_signing_key_secret_id = {}",
        hcl_string(safety_signing_key_secret_id)
    );
    let _ = writeln!(out);

    let _ = writeln!(out, "machine_type          = {}", hcl_string(machine_type));
    let _ = writeln!(out, "disk_size_gb          = {}", deploy.disk_size_gb);
    let _ = writeln!(
        out,
        "postgres_data_disk_gb = {}",
        deploy.postgres_data_disk_gb
    );
    let _ = writeln!(out);

    // blob cache の on/off は features.blob_cache が真実源。sizing は deploy から取る。
    let _ = writeln!(out, "blob_cache_enabled   = {blob_cache_enabled}");
    let _ = writeln!(out, "blob_cache_size_gb   = {}", deploy.blob_cache_size_gb);
    let _ = writeln!(
        out,
        "blob_cache_ttl_hours = {}",
        deploy.blob_cache_ttl_hours
    );
    let _ = writeln!(
        out,
        "blob_cache_path      = {}",
        hcl_string(blob_cache_path)
    );
    let _ = writeln!(out);

    let _ = writeln!(out, "rate_limit_enabled    = {}", deploy.rate_limit_enabled);
    let _ = writeln!(
        out,
        "rate_limit_per_second = {}",
        deploy.rate_limit_per_second
    );
    let _ = writeln!(out, "rate_limit_burst      = {}", deploy.rate_limit_burst);
    let _ = writeln!(out);

    let _ = writeln!(out, "backup_enabled        = {}", deploy.backup_enabled);
    let _ = writeln!(
        out,
        "backup_retention_days = {}",
        deploy.backup_retention_days
    );

    // --- index / moderation stack（#615） ---
    // secret はここでも ID のみ。値・credential は startup 時に Secret Manager から取得される。
    let safety = config.raw.safety.clone().unwrap_or_default();
    let provider_name = |entry: Option<&crate::safety_config::SafetyProviderEntry>| {
        entry
            .map(|e| e.provider.trim().to_string())
            .unwrap_or_default()
    };
    let provider_required = |entry: Option<&crate::safety_config::SafetyProviderEntry>| {
        entry.map(|e| e.required).unwrap_or(false)
    };
    let optional_secret = |value: &Option<String>| {
        value
            .as_deref()
            .map(str::trim)
            .unwrap_or_default()
            .to_string()
    };
    let suspected_visibility = safety
        .moderation
        .suspected_signal_visibility
        .map(|visibility| match visibility {
            crate::safety_config::SignalVisibility::Local => "local",
            crate::safety_config::SignalVisibility::SubscribedNodes => "subscribed_nodes",
            crate::safety_config::SignalVisibility::Public => "public",
        })
        .unwrap_or_default();

    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "deploy_indexer_stack              = {}",
        deploy.deploy_indexer_stack
    );
    let _ = writeln!(
        out,
        "cn_indexer_image                  = {}",
        hcl_string(deploy.cn_indexer_image.trim())
    );
    let _ = writeln!(
        out,
        "arcadedb_image                    = {}",
        hcl_string(deploy.arcadedb_image.trim())
    );
    let _ = writeln!(
        out,
        "indexer_data_disk_gb              = {}",
        deploy.indexer_data_disk_gb
    );
    let _ = writeln!(
        out,
        "relation_analyze_interval_minutes = {}",
        deploy.relation_analyze_interval_minutes
    );
    let _ = writeln!(
        out,
        "indexer_own_relay                 = {}",
        config.enabled(crate::Capability::IrohRelay)
    );
    let _ = writeln!(
        out,
        "indexer_external_relay_urls       = {}",
        hcl_string_list(&deploy.indexer_external_relay_urls)
    );
    let _ = writeln!(
        out,
        "indexer_retention_days            = {}",
        hcl_string(
            &deploy
                .indexer_retention_days
                .map(|days| days.to_string())
                .unwrap_or_default()
        )
    );
    let _ = writeln!(
        out,
        "indexer_capacity_rows             = {}",
        hcl_string(
            &deploy
                .indexer_capacity_rows
                .map(|rows| rows.to_string())
                .unwrap_or_default()
        )
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "channel_secret_key_secret_id = {}",
        hcl_string(&optional_secret(&deploy.channel_secret_key_secret_id))
    );
    let _ = writeln!(
        out,
        "legal_data_key_secret_id     = {}",
        hcl_string(&optional_secret(&deploy.legal_data_key_secret_id))
    );
    let _ = writeln!(
        out,
        "arcadedb_password_secret_id  = {}",
        hcl_string(&optional_secret(&deploy.arcadedb_password_secret_id))
    );
    let _ = writeln!(
        out,
        "arachnid_username_secret_id  = {}",
        hcl_string(&optional_secret(&deploy.arachnid_username_secret_id))
    );
    let _ = writeln!(
        out,
        "arachnid_password_secret_id  = {}",
        hcl_string(&optional_secret(&deploy.arachnid_password_secret_id))
    );
    let _ = writeln!(
        out,
        "vlm_api_key_secret_id        = {}",
        hcl_string(&optional_secret(&deploy.vlm_api_key_secret_id))
    );
    // secret ID 群と同じ段落に置くと terraform fmt が `=` を揃え直すため、段落を分ける（#1082）。
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "moderation = {{ api_base_url = {}, model = {}, config_version = {}, rpm = {}, rpd = {}, tpm = {}, image_tokens = {} }}",
        hcl_string(&deploy.moderation.api_base_url),
        hcl_string(&deploy.moderation.model),
        hcl_string(&deploy.moderation.config_version),
        deploy.moderation.rpm,
        deploy.moderation.rpd,
        deploy.moderation.tpm,
        deploy.moderation.image_tokens,
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "safety_provider_known_csam            = {}",
        hcl_string(&provider_name(safety.providers.known_csam.as_ref()))
    );
    let _ = writeln!(
        out,
        "safety_provider_known_csam_required   = {}",
        provider_required(safety.providers.known_csam.as_ref())
    );
    let _ = writeln!(
        out,
        "safety_provider_general               = {}",
        hcl_string(&provider_name(safety.providers.general.as_ref()))
    );
    let _ = writeln!(
        out,
        "safety_provider_general_required      = {}",
        provider_required(safety.providers.general.as_ref())
    );
    let _ = writeln!(
        out,
        "safety_provider_unknown_csam          = {}",
        hcl_string(&provider_name(safety.providers.unknown_csam.as_ref()))
    );
    let _ = writeln!(
        out,
        "safety_provider_unknown_csam_required = {}",
        provider_required(safety.providers.unknown_csam.as_ref())
    );
    let _ = writeln!(
        out,
        "safety_emit_signed_events             = {}",
        safety.events.emit_signed_moderation_events
    );
    let _ = writeln!(
        out,
        "safety_suspected_threshold            = {}",
        safety.moderation.suspected_threshold.unwrap_or(0)
    );
    let _ = writeln!(
        out,
        "safety_suspected_signal_visibility    = {}",
        hcl_string(suspected_visibility)
    );
    let _ = writeln!(
        out,
        "safety_operator_review                = {}",
        safety.moderation.operator_review
    );
    let _ = writeln!(
        out,
        "safety_general_action                 = {}",
        hcl_string(
            safety
                .moderation
                .general_action
                .map(|action| action.as_str())
                .unwrap_or("")
        )
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "vlm_api_base_url         = {}",
        hcl_string(
            deploy
                .vlm_api_base_url
                .as_deref()
                .map(str::trim)
                .unwrap_or("")
        )
    );
    let _ = writeln!(
        out,
        "vlm_model                = {}",
        hcl_string(deploy.vlm_model.as_deref().map(str::trim).unwrap_or(""))
    );
    let _ = writeln!(
        out,
        "vlm_response_format      = {}",
        hcl_string(
            deploy
                .vlm_response_format
                .as_deref()
                .map(str::trim)
                .unwrap_or("")
        )
    );
    let _ = writeln!(
        out,
        "vlm_api_timeout_secs     = {}",
        deploy.vlm_api_timeout_secs
    );
    let _ = writeln!(
        out,
        "media_fetch_max_bytes    = {}",
        deploy.media_fetch_max_bytes
    );
    let _ = writeln!(
        out,
        "media_fetch_timeout_secs = {}",
        deploy.media_fetch_timeout_secs
    );

    // ユーザー向け読み取り面（索引 query / 信頼 read）の環境変数 gate。features の
    // community_index / community_local_trust を真実源として導出する。環境変数が真でも、
    // `cn-cli readiness` の全項目合格記録（有効化の関門）が無ければ面は公開されない。
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "index_query_enabled                    = {}",
        config.enabled(crate::Capability::CommunityIndex)
    );
    let _ = writeln!(
        out,
        "trust_read_enabled                     = {}",
        config.enabled(crate::Capability::CommunityLocalTrust)
    );
    let relation_distance_optout_min_proximity = deploy
        .relation_distance_optout_min_proximity
        .map(|value| value.to_string())
        .unwrap_or_default();
    let _ = writeln!(
        out,
        "relation_distance_optout_min_proximity = {}",
        hcl_string(&relation_distance_optout_min_proximity)
    );

    // operator-config.yaml 自体を VM に配置して manifest endpoint / report_endpoint gating を
    // 有効化する。中身はこの tfvars には埋めず、Terraform 側の .tf で file() する。
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "# operator-config.yaml を VM へ配置して public manifest endpoint /"
    );
    let _ = writeln!(
        out,
        "# report_endpoint gating を有効化する。env dir からの相対 path を指定する:"
    );
    let _ = writeln!(out, "# operator_config_path = \"operator-config.yaml\"");

    out
}
