import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '../../..');
const publicDir = path.join(root, 'apps/lp/public');
const escape = (text) => text.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const inline = (text) => escape(text).replace(/`([^`]+)`/g, '<code>$1</code>').replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');

// Render only the constructs used by the canonical documents; never execute HTML.
function render(source) {
  return source.trim().split(/\n\s*\n/).map((block) => {
    const heading = block.match(/^(#{1,3}) (.+)$/);
    if (heading) return `<h${heading[1].length}>${inline(heading[2])}</h${heading[1].length}>`;
    const lines = block.split('\n');
    if (lines.every((line) => /^- /.test(line))) {
      return `<ul>${lines.map((line) => `<li>${inline(line.slice(2))}</li>`).join('\n')}</ul>`;
    }
    if (lines.every((line) => /^\d+\. /.test(line))) {
      return `<ol>${lines.map((line) => `<li value="${line.match(/^\d+/)[0]}">${inline(line.replace(/^\d+\. /, ''))}</li>`).join('\n')}</ol>`;
    }
    if (lines.every((line) => line.startsWith('> '))) {
      return `<blockquote>${lines.map((line) => `<p>${inline(line.slice(2))}</p>`).join('\n')}</blockquote>`;
    }
    return `<p>${inline(block).replaceAll('\n', '<br>')}</p>`;
  }).join('\n');
}

const check = process.argv.includes('--check');
let stale = false;
for (const [route, file, label] of [
  ['privacy', 'privacy-policy.md', 'プライバシーポリシー'],
  ['terms', 'terms-of-service.md', '利用規約'],
]) {
  const source = readFileSync(path.join(root, 'docs/legal', file), 'utf8').replaceAll('\r\n', '\n');
  const hash = createHash('sha256').update(source).digest('hex');
  const html = `<!doctype html>
<!-- Generated by apps/lp/scripts/sync-legal.mjs from docs/legal/${file}; sha256=${hash} -->
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>クライアントの${label} | kukuri</title>
  <meta name="description" content="kukuriの${label}の全文。日本語正文。">
  <link rel="canonical" href="https://kukuri.app/${route}/">
  <style>
    :root { color-scheme: light; }
    * { box-sizing: border-box; }
    body { margin: 0; background: #f6f4f1; color: #1c1a17; font: 1rem/1.85 system-ui, sans-serif; }
    header, main, footer { max-width: 52rem; margin: auto; padding: 1.5rem; }
    main { background: white; overflow-wrap: anywhere; }
    nav { display: flex; flex-wrap: wrap; gap: 1rem; }
    a { color: #9c4f20; text-underline-offset: .2em; }
    a:focus-visible { outline: 3px solid #0b6e66; outline-offset: 4px; }
    h1 { font-size: clamp(1.6rem, 5vw, 2.2rem); line-height: 1.4; }
    h2 { font-size: 1.35rem; margin-top: 2.5rem; line-height: 1.5; }
    li { margin-block: .6rem; }
    ul, ol { padding-left: 1.6rem; }
    blockquote { margin: 1rem 0; padding: .5rem 1rem; border-left: 3px solid #d77d45; background: #f6f4f1; }
    code { font: inherit; }
    .notice { color: #4a4540; }
  </style>
</head>
<body>
<!--email_off-->
  <header><nav aria-label="サイト内ナビゲーション"><a href="/">kukuri ホーム</a><a href="/en/" lang="en">English home</a><a href="/terms/">クライアント利用規約</a><a href="/privacy/">クライアントプライバシーポリシー</a></nav>
  <p class="notice">クライアント用文書（日本語正文）。Community Nodeの個別文書とは異なります。<br><span lang="en">Client document — authoritative Japanese text. Separate from each Community Node's policies.</span></p></header>
  <main id="content"><article>
${render(source)}
  </article></main>
  <footer><a href="https://github.com/kukuri-app/kukuri/blob/main/docs/legal/${file}">正文のソース（GitHub）</a> · <a href="mailto:ops@kukuri.app">お問い合わせ</a></footer>
<!--/email_off-->
</body>
</html>
`;
  const target = path.join(publicDir, route, 'index.html');
  const current = existsSync(target) ? readFileSync(target, 'utf8').replaceAll('\r\n', '\n') : '';
  if (current === html) continue;
  if (check) {
    process.stderr.write(`Out of sync: ${target}\n`);
    stale = true;
  } else {
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, html);
    process.stdout.write(`Generated: ${target}\n`);
  }
}
if (stale) process.exitCode = 1;
