// @generated by `cargo xtask ipc-types` from Rust IPC types. DO NOT EDIT.
// 手で編集せず、Rust 側(crates/app-api/src/views.rs ほか)を変更して再生成すること。

export type DeleteDomeInput = { spatial_context: SpatialContextV1, instance_id: string, expected_generation: number, operation_id: string, };

export type PendingDomeDeletionView = { request: DeleteDomeInput, title: string, deleted: boolean, };

export type DeleteDomeView = { instance_id: string, generation: number, deleted: boolean, cleanup_pending: boolean, };

export type TimelineCursor = { created_at: number, object_id: string, };

export type ChannelAudienceKind = "invite_only" | "friend_only" | "friend_plus";

export type ChannelSharingState = "open" | "frozen";

export type DiscoveryMode = "static_peer" | "seeded_dht";

export type ConnectMode = "direct_only" | "direct_or_relay";

export type ConnectionPath = "direct_p2p" | "relay_supported_p2p" | "relay_fallback";

export type SocialConnectionKind = "following" | "followed" | "muted" | "blocking" | "blocked_by";

export type BlobViewStatus = "Missing" | "Available" | "Pinned";

export type DeliveryState = "Live" | "DurableRecovering" | "DurableReady" | "Offline";

export type NotificationKind = "mention" | "reply" | "repost" | "quote_repost" | "direct_message" | "followed";

export type ChannelAccessTokenKind = "invite" | "grant" | "share";

export type ProfileAssetView = { hash: string, mime: string, bytes: number, role: 'profile_avatar', };

export type AttachmentView = { hash: string, mime: string, bytes: number, role: string, status: BlobViewStatus, provenance?: ContentProvenanceView | null, };

export type BlobMediaPayload = { bytes_base64: string, mime: string, };

export type ContentDisplaySettings = { adult_content_enabled: boolean, };

export type ReplyPreviewAuthorView = { pubkey: string, name?: string | null, display_name?: string | null, picture_asset?: ProfileAssetView | null, };

export type ReplyPreviewView = { object_id: string, topic: string, author: ReplyPreviewAuthorView, content: string, attachments: Array<AttachmentView>, content_labels?: Array<string> | null, root_id?: string | null, reply_to?: string | null, };

export type ReactionKeyView = { reaction_key_kind: string, normalized_reaction_key: string, emoji?: string | null, custom_asset?: CustomReactionAssetView | null, };

export type ReactionSummaryView = { reaction_key_kind: string, normalized_reaction_key: string, emoji?: string | null, custom_asset?: CustomReactionAssetView | null, count: number, };

export type ReactionStateView = { target_object_id: string, source_replica_id: string, reaction_summary: Array<ReactionSummaryView>, my_reactions: Array<ReactionKeyView>, };

export type RecentReactionView = { reaction_key_kind: string, normalized_reaction_key: string, emoji?: string | null, custom_asset?: CustomReactionAssetView | null, updated_at: number, };

export type CustomReactionAssetView = { asset_id: string, owner_pubkey: string, blob_hash: string, search_key: string, mime: string, bytes: number, width: number, height: number, };

export type RepostSourceView = { source_object_id: string, source_topic_id: string, source_author_pubkey: string, source_author_name?: string | null, source_author_display_name?: string | null, source_author_picture_asset?: ProfileAssetView | null, source_object_kind: string, content: string, attachments: Array<AttachmentView>, content_labels?: Array<string> | null, reply_to?: string | null, root_id?: string | null, };

export type ContentObservationView = { node_base_url: string, capability: string, observed_at: number, };

export type ContentProvenanceView = { canonical_source: string, observed_via: Array<ContentObservationView>, };

export type PostWithdrawalView = { withdrawn_at: number, replacement_object_id?: string | null, reason_visibility: string, reason?: string | null, };

export type PostView = { object_id: string, envelope_id: string, author_pubkey: string, author_name?: string | null, author_display_name?: string | null, author_picture_asset?: ProfileAssetView | null, following: boolean, followed_by: boolean, mutual: boolean, friend_of_friend: boolean, provenance?: ContentProvenanceView | null, withdrawal?: PostWithdrawalView | null, content: string, content_status: BlobViewStatus, attachments: Array<AttachmentView>, content_labels?: Array<string> | null, created_at: number, reply_to?: string | null, reply_preview?: ReplyPreviewView | null, root_id?: string | null, object_kind: string, published_topic_id?: string | null, origin_topic_id?: string | null, repost_of?: RepostSourceView | null, repost_commentary?: string | null, is_threadable: boolean, channel_id?: string | null, audience_label: string, reaction_summary?: Array<ReactionSummaryView> | null, my_reactions?: Array<ReactionKeyView> | null, };

export type BookmarkedPostView = { bookmarked_at: number, post: PostView, };

export type AuthorSocialView = { author_pubkey: string, name?: string | null, display_name?: string | null, about?: string | null, picture_asset?: ProfileAssetView | null, updated_at?: number | null, following: boolean, followed_by: boolean, mutual: boolean, friend_of_friend: boolean, friend_of_friend_via_pubkeys: Array<string>, provenance?: ContentProvenanceView | null, muted: boolean, blocking: boolean, blocked_by: boolean, };

export type DirectMessageStatusView = { peer_pubkey: string, dm_id: string, mutual: boolean, send_enabled: boolean, peer_count: number, pending_outbox_count: number, };

export type DirectMessageTopicStatusView = { topic: string, joined: boolean, peer_count: number, connected_peers: Array<string>, status_detail: string, last_error?: string | null, };

export type DirectMessageMessageView = { dm_id: string, message_id: string, sender_pubkey: string, recipient_pubkey: string, created_at: number, text: string, reply_to_message_id?: string | null, attachments: Array<AttachmentView>, outgoing: boolean, delivered: boolean, };

export type DirectMessageConversationView = { dm_id: string, peer_pubkey: string, peer_name?: string | null, peer_display_name?: string | null, peer_picture_asset?: ProfileAssetView | null, updated_at: number, last_message_at?: number | null, last_message_id?: string | null, last_message_preview?: string | null, status: DirectMessageStatusView, };

export type NotificationView = { notification_id: string, kind: NotificationKind, actor_pubkey: string, actor_name?: string | null, actor_display_name?: string | null, actor_picture_asset?: ProfileAssetView | null, source_envelope_id?: string | null, source_replica_id?: string | null, topic_id?: string | null, channel_id?: string | null, object_id?: string | null, thread_root_object_id?: string | null, dm_id?: string | null, message_id?: string | null, preview_text?: string | null, content_labels?: Array<string> | null, created_at: number, received_at: number, read_at?: number | null, };

export type NotificationStatusView = { unread_count: number, };

export type TimelineView = { items: Array<PostView>, next_cursor?: TimelineCursor | null, };

export type DirectMessageTimelineView = { items: Array<DirectMessageMessageView>, next_cursor?: TimelineCursor | null, };

export type JoinedPrivateChannelView = { topic_id: string, channel_id: string, label: string, creator_pubkey: string, owner_pubkey: string, joined_via_pubkey?: string | null, audience_kind: ChannelAudienceKind, is_owner: boolean, current_epoch_id: string, archived_epoch_ids: Array<string>, sharing_state: ChannelSharingState, rotation_required: boolean, participant_count: number, stale_participant_count: number, entry_dome_instance_id?: string | null, };

export type PrivateChannelEpochCapability = { epoch_id: string, namespace_secret_hex: string, };

export type PrivateChannelCapability = { topic_id: string, channel_id: string, label: string, creator_pubkey: string, owner_pubkey: string, joined_via_pubkey?: string | null, audience_kind: ChannelAudienceKind, current_epoch_id: string, current_epoch_secret_hex: string, archived_epochs: Array<PrivateChannelEpochCapability>, rotation_required: boolean, participant_count: number, stale_participant_count: number, namespace_secret_hex: string, };

export type ChannelAccessTokenExport = { kind: ChannelAccessTokenKind, token: string, };

export type ChannelAccessTokenPreview = { kind: ChannelAccessTokenKind, topic_id: string, channel_id: string, channel_label: string, owner_pubkey: string, inviter_pubkey?: string | null, sponsor_pubkey?: string | null, epoch_id: string, };

export type TopicSyncStatus = { topic: string, joined: boolean, delivery_state: DeliveryState, peer_count: number, connected_peers: Array<string>, docs_assist_peer_ids: Array<string>, configured_peer_ids: Array<string>, missing_peer_ids: Array<string>, active_path: ConnectionPath, rendezvous_peer_ids: Array<string>, fallback_peer_ids: Array<string>, last_received_at?: number | null, last_docs_activity_at?: number | null, status_detail: string, last_error?: string | null, };

export type DiscoveryStatus = { mode: DiscoveryMode, connect_mode: ConnectMode, active_path: ConnectionPath, fallback_peer_ids: Array<string>, env_locked: boolean, configured_seed_peer_ids: Array<string>, bootstrap_seed_peer_ids: Array<string>, manual_ticket_peer_ids: Array<string>, connected_peer_ids: Array<string>, docs_assist_peer_ids: Array<string>, blob_assist_peer_ids: Array<string>, local_endpoint_id: string, last_discovery_error?: string | null, };

export type SyncStatus = { connected: boolean, delivery_state: DeliveryState, last_sync_ts?: number | null, peer_count: number, pending_events: number, status_detail: string, last_error?: string | null, configured_peers: Array<string>, subscribed_topics: Array<string>, active_path: ConnectionPath, fallback_peer_ids: Array<string>, topic_diagnostics: Array<TopicSyncStatus>, local_author_pubkey: string, discovery: DiscoveryStatus, gossip_disabled_topics: Array<string>, gossip_disabled_channels: Array<string>, };

export type LiveSessionStatus = "Scheduled" | "Live" | "Paused" | "Ended";

export type LiveSessionView = { session_id: string, host_pubkey: string, title: string, description: string, status: LiveSessionStatus, started_at: number, ended_at?: number | null, viewer_count: number, joined_by_me: boolean, channel_id?: string | null, audience_label: string, };

export type GameRoomStatus = "Waiting" | "Running" | "Paused" | "Ended";

export type GameRoomKind = "score_game" | "metaverse_room";

export type GameScoreView = { participant_id: string, label: string, score: number, };

export type MetaverseAssetKind = "vrm" | "glb" | "texture" | "other";

export type MetaverseAssetBudgetMetadataV1 = { stored_bytes: number, texture_width?: number | null, texture_height?: number | null, decoded_texture_bytes: number, model_triangles: number, model_primitives: number, };

export type MetaverseAssetRef = { kind: MetaverseAssetKind, blob_hash: string, mime_type?: string | null, size_bytes?: number | null, name?: string | null, budget_metadata?: MetaverseAssetBudgetMetadataV1 | null, };

export type DomeResourceBudget = { max_persistent_props: number, max_texture_bytes: number, max_texture_dimension: number, max_model_bytes: number, max_model_triangles: number, max_colliders: number, max_rigid_bodies: number, max_snapshot_hz: number, };

export type PlayerResourceBudget = { max_guest_props: number, max_guest_prop_bytes: number, max_avatar_asset_bytes: number, max_prop_spawns_per_minute: number, max_interactions_per_second: number, max_input_bytes_per_second: number, max_proposals_per_ten_minutes_per_slot: number, max_impulse_centimeters: number, max_audio_frames_per_second: number, max_audio_bytes_per_second: number, };

export type HostResourceBudget = { max_participants: number, max_simulated_rigid_bodies: number, max_snapshot_bytes_per_second: number, max_session_asset_bytes: number, };

export type ClientResourceBudget = { max_rendered_avatars: number, max_texture_memory_bytes: number, max_rendered_triangles: number, max_interpolated_bodies: number, max_neighbor_domes: number, cache_capacity_bytes: number, max_concurrent_audio_streams: number, max_audio_jitter_frames: number, };

export type MetaverseResourceBudgetConfig = { dome: DomeResourceBudget, player: PlayerResourceBudget, host: HostResourceBudget, client: ClientResourceBudget, };

export type MetaverseBudgetScope = "dome" | "player" | "host" | "client";

export type MetaverseBudgetResource = "persistent_props" | "guest_props" | "texture_bytes" | "texture_dimension" | "model_bytes" | "model_triangles" | "colliders" | "rigid_bodies" | "participants" | "avatar_asset_bytes" | "prop_spawn_rate" | "interaction_rate" | "input_bandwidth" | "proposal_rate" | "impulse" | "snapshot_frequency" | "snapshot_bandwidth" | "session_asset_bytes" | "rendered_avatars" | "texture_memory" | "rendered_triangles" | "interpolated_bodies" | "neighbor_domes" | "cache_capacity" | "asset_format" | "audio_frame_rate" | "audio_bandwidth" | "concurrent_audio_streams" | "audio_jitter_frames";

export type MetaverseResourceRejectionReason = "limit_exceeded" | "rate_exceeded" | "invalid_value" | "unverified_asset";

export type MetaverseResourceRejection = { scope: MetaverseBudgetScope, resource: MetaverseBudgetResource, reason: MetaverseResourceRejectionReason, observed: number, limit: number, };

export type MetaverseResourceMetricCountV1 = { code: string, count: number, };

export type MetaverseResourceMetricsV1 = { rejected_total: number, rejection_counts: Array<MetaverseResourceMetricCountV1>, participant_high_water: number, rigid_body_high_water: number, snapshot_bytes: number, snapshot_throttled: number, };

export type MetaversePrimitive = "cube" | "sphere";

export type DomeDirection = "north" | "east" | "south" | "west";

export type DomeBoundaryStateV1 = "closed" | "offline" | "draining" | "blocked" | "loading" | "ready" | "denied" | "full" | "unhosted" | "error" | "stale";

export type DomeTransitionDenialReasonV1 = "host_unavailable" | "access_denied" | "owners_blocked" | "visitor_blocked" | "capacity_full" | "assets_unavailable" | "stale_topology" | "stale_session" | "invalid_ticket";

export type DomeTransitionPhaseV1 = "closed" | "loading" | "ready" | "preparing" | "provisional" | "committing" | "committed" | "failed";

export type DomeTransitionAdmissionRequestV1 = { transition_id: string, connection_id: string, topology_digest: string, spatial_context: SpatialContextV1, source_instance_id: string, source_instance_generation: number, target_instance_id: string, target_instance_generation: number, participant_pubkey: string, direction: DomeDirection, requested_at: number, };

export type DomeTransitionAdmissionTicketV1 = { request: DomeTransitionAdmissionRequestV1, target_lease_epoch: number, target_session_id: string, expires_at: number, };

export type DomeTransitionAccessDecisionV1 = { "status": "allowed" } | { "status": "denied", reason: DomeTransitionDenialReasonV1, };

export type DomeMaterialPreset = "concrete" | "stone" | "metal" | "wood";

export type DomeSurfaceCustomizationV1 = { wall_material: DomeMaterialPreset, floor_material: DomeMaterialPreset, wall_texture?: MetaverseAssetRef | null, floor_texture?: MetaverseAssetRef | null, };

export type DomeEnvironmentV1 = { key_light_milli: number, ambient_light_milli: number, fog_density_micros: number, gravity_milli: number, };

export type MetaverseInteractionKind = "grab" | "throw" | "push" | "sit";

export type MetaverseColliderV1 = { "shape": "capsule", center: [number, number, number], radius: number, half_height: number, } | { "shape": "cuboid", center: [number, number, number], half_extents: [number, number, number], };

export type MetaversePersistentPropV1 = { prop_id: string, asset_ref?: MetaverseAssetRef | null, primitive_fallback: MetaversePrimitive, position: [number, number, number], rotation: [number, number, number], scale: [number, number, number], visual_only: boolean, interactions: Array<MetaverseInteractionKind>, collider?: MetaverseColliderV1 | null, };

export type DomeCustomizationV1 = { surface: DomeSurfaceCustomizationV1, environment: DomeEnvironmentV1, persistent_props: Array<MetaversePersistentPropV1>, };

export type MetaverseDomeV1 = { spec_id: string, customization: DomeCustomizationV1, };

export type SpatialContextV1 = { "kind": "topic", topic_id: string, } | { "kind": "channel", topic_id: string, channel_id: string, };

export type DomePresetRefV1 = { preset_id: string, owner_pubkey: string, revision: number, manifest_blob_hash: string, manifest_mime: string, manifest_bytes: number, };

export type DomeInstanceStatusV1 = "staging" | "active" | "tombstoned";

export type DomeRelationshipDetachV1 = { move_id: string, instance_generation: number, detached_at: number, };

export type DomeMovePhaseV1 = "preparing" | "target_staged" | "source_detached" | "target_active" | "source_tombstoned" | "completed" | "failed";

export type DomeMoveRecordV1 = { move_id: string, owner_pubkey: string, source_instance_id: string, source_context: SpatialContextV1, source_generation: number, target_instance_id: string, target_context: SpatialContextV1, target_generation: number, preset_ref: DomePresetRefV1, phase: DomeMovePhaseV1, failure_reason?: string | null, updated_at: number, };

export type DomeConnectionEndpointV1 = { instance_id: string, instance_generation: number, owner_pubkey: Pubkey, direction: DomeDirection, };

export type DomeConnectionProposalV1 = { proposal_id: string, spatial_context: SpatialContextV1, proposer: DomeConnectionEndpointV1, receiver: DomeConnectionEndpointV1, sequence: number, created_at: number, };

export type DomeProposalSelectionV1 = { selection_id: string, proposal_id: string, spatial_context: SpatialContextV1, receiver: DomeConnectionEndpointV1, slot_generation: number, observed_active_connection_ids: Array<string>, selected_at: number, };

export type DomeConnectionAgreementV1 = { connection_id: string, proposal_id: string, spatial_context: SpatialContextV1, proposer: DomeConnectionEndpointV1, receiver: DomeConnectionEndpointV1, activation_generation: number, };

export type DomeConnectionStatusV1 = "accepted" | "active" | "draining" | "revoked";

export type DomeConnectionTerminalReasonV1 = "owner_revoked" | "proposer_withdrew" | "proposer_slot_occupied" | "instance_detached" | "instance_deleted" | "owners_blocked";

export type DomeConnectionRecordV1 = { agreement: DomeConnectionAgreementV1, receiver_slot_generation: number, observed_active_connection_ids: Array<string>, status: DomeConnectionStatusV1, lifecycle_generation: number, lifecycle_actor: Pubkey | null, lifecycle_reason: DomeConnectionTerminalReasonV1 | null, lifecycle_deadline_at: number | null, };

export type DomeProposalDerivedStatusV1 = "proposed" | "reserved" | "accepted" | "waiting_for_slot" | "discarded";

export type DomeComponentTopologyV1 = { root_instance_id: string, instance_ids: Array<string>, connection_ids: Array<string>, coordinates_cm: { [key in string]: [number, number, number] }, };

export type DomeTopologyV1 = { spatial_context: SpatialContextV1, components: Array<DomeComponentTopologyV1>, active_connection_ids: Array<string>, topology_digest: string, };

export type DomeRejectedConnectionV1 = { connection_id: string, reason: string, };

export type DomeTopologyResolutionV1 = { topology: DomeTopologyV1, rejected_connections: Array<DomeRejectedConnectionV1>, };

export type DomeHostTargetV1 = { "kind": "owner_device", endpoint_id: string, host_pubkey: string, } | { "kind": "community_node", node_id: string, api_base_url: string, };

export type DomeHostingLeaseV1 = { lease_id: string, spatial_context: SpatialContextV1, instance_id: string, instance_generation: number, owner_pubkey: string, host: DomeHostTargetV1, manifest_blob_hash: string, manifest_version: number, epoch: number, issued_at: number, expires_at: number, };

export type DomeHostingStateKindV1 = "closed" | "owner_hosted" | "community_node_hosted" | "grace_period" | "transferring";

export type DomeHostingStateV1 = { kind: DomeHostingStateKindV1, host?: DomeHostTargetV1 | null, lease_id?: string | null, lease_epoch?: number | null, lease_expires_at?: number | null, session_id?: string | null, reason?: string | null, last_heartbeat_at?: number | null, };

export type DomeSessionInputKindV1 = { "type": "join", avatar_collider?: MetaverseColliderV1 | null, } | { "type": "leave" } | { "type": "keep_alive" } | { "type": "move", position: [number, number, number], rotation: [number, number, number], animation: string, } | { "type": "grab", prop_id: string, } | { "type": "throw", prop_id: string, impulse: [number, number, number], } | { "type": "push", prop_id: string, impulse: [number, number, number], } | { "type": "sit", prop_id: string, } | { "type": "prepare_transition", transition_id: string, direction: DomeDirection, } | { "type": "abort_transition", transition_id: string, } | { "type": "complete_transition", transition_id: string, } | { "type": "spawn_guest_prop", prop: MetaversePersistentPropV1, expires_at: number, } | { "type": "upsert_persistent_prop", prop: MetaversePersistentPropV1, } | { "type": "delete_persistent_prop", prop_id: string, };

export type DomePhysicsBodyKindV1 = "avatar" | "persistent_prop" | "guest_prop";

export type DomePhysicsBodyV1 = { entity_id: string, kind: DomePhysicsBodyKindV1, position: [number, number, number], rotation: [number, number, number], linear_velocity: [number, number, number], animation: string | null, grabbed_by: string | null, expires_at: number | null, };

export type DomePhysicsSnapshotV1 = { instance_id: string, instance_generation: number, lease_epoch: number, session_id: string, host_pubkey: string, sequence: number, simulated_at: number, sleeping: boolean, bodies: Array<DomePhysicsBodyV1>, };

export type DomeHostingView = { instance_id: string, state: DomeHostingStateV1, lease?: DomeHostingLeaseV1 | null, signed_lease_json?: string | null, signed_activation_json?: string | null, signed_close_json?: string | null, instance_manifest_json: string, preset_manifest_json?: string | null, participants: number, sleeping: boolean, resource_budget: MetaverseResourceBudgetConfig, resource_metrics: MetaverseResourceMetricsV1, };

export type DomeLayoutCandidateV1 = { operation_id: string, instance_id: string, instance_generation: number, lease_epoch: number, session_id: string, host_pubkey: string, base_manifest_revision: number, snapshot_sequence: number, captured_at: number, persistent_props: Array<MetaversePersistentPropV1>, };

export type DomeLayoutCommitV1 = { operation_id: string, instance_id: string, instance_generation: number, owner_pubkey: string, base_manifest_revision: number, next_manifest_revision: number, candidate_digest: string, manifest_blob_hash: string, committed_at: number, };

export type DomeLayoutCommitOutcome = "no_op" | "committed";

export type DomeLayoutCommitView = { outcome: DomeLayoutCommitOutcome, operation_id: string, revision: number, manifest_blob_hash: string, signed_commit_json?: string | null, hosting: DomeHostingView, };

export type DomeConnectionProposalView = { proposal: DomeConnectionProposalV1, selection?: DomeProposalSelectionV1 | null, status: DomeProposalDerivedStatusV1, terminal_reason?: DomeConnectionTerminalReasonV1 | null, connection_id: string, };

export type DomeConnectionView = { record: DomeConnectionRecordV1, };

export type DomeConnectionTopologyView = { proposals: Array<DomeConnectionProposalView>, connections: Array<DomeConnectionView>, resolution: DomeTopologyResolutionV1, };

export type MetaverseRoomPresenceV1 = { room_id: string, peer_id: string, display_name?: string | null, avatar_asset_ref?: MetaverseAssetRef | null, joined_at: number, last_seen_at: number, };

export type MetaverseSpatialAudioFrameV1 = { room_id: string, peer_id: string, position: [number, number, number], sample_rate_hz: number, samples: Array<number>, captured_at: number, };

export type MetaverseRoomChatMessageV1 = { room_id: string, message_id: string, author_peer_id: string, display_name?: string | null, body: string, created_at: number, };

export type SharedRoomObjectV1 = { object_id: string, asset_ref?: MetaverseAssetRef | null, primitive_fallback: MetaversePrimitive, position: [number, number, number], rotation: [number, number, number], scale: [number, number, number], updated_by: string, updated_at: number, };

export type MetaverseRoomEventV1 = { "type": "presence_join", presence: MetaverseRoomPresenceV1, } | { "type": "presence_leave", room_id: string, peer_id: string, left_at: number, } | { "type": "chat_message", message: MetaverseRoomChatMessageV1, } | { "type": "spatial_audio_frame", frame: MetaverseSpatialAudioFrameV1, };

export type MetaverseRoomEventEnvelopeContentV1 = { event_id: string, topic_id: string, channel_id?: string | null, room_id: string, spatial_context: SpatialContextV1, instance_generation: number, session_id: string, peer_id: string, seq: number, sent_at: number, event: MetaverseRoomEventV1, };

export type MetaverseRoomSpawnV1 = { position: [number, number, number], rotation: [number, number, number], };

export type MetaverseRoomStateV1 = { world_version: number, instance_id: string, spatial_context: SpatialContextV1, instance_generation: number, instance_status: DomeInstanceStatusV1, relationship_detach?: DomeRelationshipDetachV1 | null, replacement_instance_id?: string | null, preset_ref: DomePresetRefV1, session_id: string, max_peers?: number | null, dome: MetaverseDomeV1, default_spawn: MetaverseRoomSpawnV1, asset_refs: Array<MetaverseAssetRef>, chat_history?: Array<MetaverseRoomChatMessageV1> | null, };

export type GameRoomView = { room_id: string, host_pubkey: string, title: string, description: string, status: GameRoomStatus, phase_label?: string | null, scores: Array<GameScoreView>, room_kind: GameRoomKind, metaverse?: MetaverseRoomStateV1 | null, dome_hosting?: DomeHostingStateV1 | null, manifest_blob_hash: string, updated_at: number, channel_id?: string | null, audience_label: string, };

export type MetaverseRoomEventView = { envelope_id: string, content: MetaverseRoomEventEnvelopeContentV1, envelope: Record<string, unknown>, received_at: number, source_peer: string, };

export type Pubkey = string;

export type TopicId = string;

export type ChannelId = string;

export type ChannelRef = { "kind": "public" } | { "kind": "private_channel", channel_id: ChannelId, };

export type TimelineScope = { "kind": "public" } | { "kind": "all_joined" } | { "kind": "channel", channel_id: ChannelId, };

export type SeedPeer = { endpoint_id: string, addr_hint?: string | null, };

export type Profile = { pubkey: Pubkey, name?: string | null, display_name?: string | null, about?: string | null, picture_asset?: ProfileAssetView | null, updated_at: number, };

export type PrivateChannelInvitePreview = { channel_id: ChannelId, topic_id: TopicId, channel_label: string, inviter_pubkey: Pubkey, owner_pubkey: Pubkey, epoch_id: string, expires_at?: number | null, namespace_secret_hex: string, };

export type FriendOnlyGrantPreview = { channel_id: ChannelId, topic_id: TopicId, channel_label: string, owner_pubkey: Pubkey, epoch_id: string, expires_at?: number | null, namespace_secret_hex: string, };

export type FriendPlusSharePreview = { channel_id: ChannelId, topic_id: TopicId, channel_label: string, owner_pubkey: Pubkey, sponsor_pubkey: Pubkey, epoch_id: string, expires_at?: number | null, namespace_secret_hex: string, share_token_id: string, };

export type DiscoveryConfig = { mode: DiscoveryMode, connect_mode: ConnectMode, env_locked: boolean, seed_peers: Array<SeedPeer>, };

export type CommunityNodeSeedPeer = { endpoint_id: string, addr_hint?: string | null, };

export type CommunityNodeResolvedUrls = { public_base_url: string, connectivity_urls: Array<string>, seed_peers?: Array<CommunityNodeSeedPeer> | null, };

export type CommunityNodeNodeConfig = { base_url: string, resolved_urls?: CommunityNodeResolvedUrls | null, 
/**
 * #1056: この node が発行した content advisory(成人向け表現の推定)を採用するか。
 * 既定 true(node を設定すること自体が ADR 0046 §6.1 の opt-in)。false の node へは
 * タイムライン向け一括照会を送らず、「見つける」の index 応答の advisory も採用しない。
 */
content_advisory_enabled?: boolean | null, };

export type CommunityNodeConfig = { nodes: Array<CommunityNodeNodeConfig>, 
/**
 * #1061: 信頼値による表示判断で採用する node の優先順位（上位から採る）。
 * 空なら、この機能による非表示を行わない。設定済み node に限る。
 */
trust_node_priority?: Array<string> | null, };

export type CommunityNodeAuthState = { authenticated: boolean, expires_at?: number | null, };

export type CommunityNodeConsentItem = { policy_slug: string, policy_version: number, title: string, body?: string | null, required: boolean, accepted_at?: number | null, 
/**
 * その policy_slug で過去に同意した最大 version（version 不問）。
 * `accepted_at` が None でこれが Some なら、版が上がって再同意が必要な「更新」を意味する。
 */
previously_accepted_version?: number | null, effective_date?: string | null, language?: string | null, policy_snapshot_revision?: string | null, };

export type CommunityNodeConsentStatus = { all_required_accepted: boolean, items: Array<CommunityNodeConsentItem>, policy_snapshot_revision?: string | null, };

export type CommunityNodePolicyDocument = { policy_slug: string, policy_version: number, title: string, body_markdown: string, required: boolean, 
/**
 * operator config の `legal.documents[].kind`(#1192)。slug は operator が自由に決める
 * ため、client が文書の役割(利用規約 / 権利侵害申出ポリシー等)を判別するのに使う。
 * node が現在公開していない slug(退役 revision 等)では欠落する。
 */
policy_kind?: string | null, effective_date?: string | null, language?: string | null, policy_snapshot_revision?: string | null, authoritative_language?: string | null, reference_translation: boolean, translation_revision?: number | null, translation_of_version?: number | null, fallback: boolean, requested_language?: string | null, material_change: boolean, requires_reconsent: boolean, is_current: boolean, publication_status?: string | null, published_at?: string | null, retired_at?: string | null, previous_policy_version?: number | null, previous_policy_snapshot_revision?: string | null, next_policy_version?: number | null, next_policy_snapshot_revision?: string | null, };

export type CommunityNodePoliciesResponse = { policies: Array<CommunityNodePolicyDocument>, policy_snapshot_revision?: string | null, };

export type FetchCommunityNodePoliciesRequest = { base_url: string, language?: string | null, };

export type CommunityNodeConsentDocumentRef = { policy_slug: string, policy_version: number, policy_snapshot_revision?: string | null, };

export type CommunityNodeLocalConsentRecord = { policy_slug: string, policy_version: number, policy_snapshot_revision?: string | null, accepted_at: number, language: string, app_version: string, };

export type CommunityNodeLocalConsentState = { records: Array<CommunityNodeLocalConsentRecord>, withdrawn_at?: number | null, };

export type CommunityNodeAdmissionRejectionCode = "INVITE_REQUIRED" | "INVITE_INVALID" | "INVITE_EXPIRED" | "INVITE_EXHAUSTED" | "INVITE_REVOKED" | "NOT_ALLOWLISTED" | "BANNED";

export type CommunityNodeAdmissionRejection = { code: CommunityNodeAdmissionRejectionCode, message: string, };

export type CommunityNodeSessionPhase = "idle" | "connecting" | "authenticating" | "accepting" | "refreshing" | "ready" | "retrying" | "awaiting_admission";

export type CommunityNodeNodeStatus = { base_url: string, auth_state: CommunityNodeAuthState, consent_state?: CommunityNodeConsentStatus | null, 
/**
 * #857: Node 別ローカル同意記録。空 = 未同意(この node へは通信しない)。
 */
local_consent?: CommunityNodeLocalConsentState | null, 
/**
 * #857: 版が上がって再同意が必要な状態(公開カタログ照合で検出)。
 */
consent_update_pending?: boolean | null, resolved_urls?: CommunityNodeResolvedUrls | null, last_error?: string | null, invite_code_saved: boolean, admission_rejection?: CommunityNodeAdmissionRejection | null, session_phase?: CommunityNodeSessionPhase | null, retry_after?: number | null, restart_required: boolean, };

export type CommunityNodeCapabilityScope = { available_enabled: Array<string>, planned_enabled: Array<string>, };

export type CommunityNodeAuthorityScope = { applies_to: Array<string>, does_not_apply_to: Array<string>, };

export type CommunityNodeP2pBoundary = { identity_authority: boolean, profile_canonical_store: boolean, social_graph_canonical_store: boolean, content_truth_source: boolean, network_wide_authority: boolean, };

export type CommunityNodeLegalDocument = { slug: string, version: number, effective_date: string, language: string, required: boolean, url: string, };

export type CommunityNodeManifest = { node_id: string, node_name: string, node_role: string, server_name: string, manifest_version: string, capability_scope: CommunityNodeCapabilityScope, authority_scope: CommunityNodeAuthorityScope, p2p_boundary: CommunityNodeP2pBoundary, abuse_contact: string, 
/**
 * node が公開する通報受付 endpoint(#310)。未公開の場合は空文字。
 * client は空なら `abuse_contact` を mailto / copyable contact として案内する。
 */
report_endpoint: string, 
/**
 * node が公開する権利侵害申出画面。未公開の場合は空文字。
 */
rights_request_url?: string | null, rights_request_policy_url?: string | null, rights_request_initial_response_target_days?: number | null, terms_url: string, privacy_url: string, external_transmission_url?: string | null, moderation_policy_url: string, abuse_policy_url?: string | null, data_retention_url?: string | null, legal_documents?: Array<CommunityNodeLegalDocument> | null, };

export type CommunityNodeManifestFetchStatus = "ok" | "absent";

export type CommunityNodeManifestFetch = { status: CommunityNodeManifestFetchStatus, manifest?: CommunityNodeManifest | null, };

export type CommunityNodeIndexQueryRequest = { base_url: string, query?: string | null, scope_kind?: IndexScopeKind | null, scope_id?: string | null, 
/**
 * scope_kind が private_channel のとき必須。所属証明(channel secret)を参加中
 * チャンネルの capability から引くために使う(#711)。
 */
topic_id?: string | null, limit?: number | null, };

export type CommunityNodeIndexQueryError = { code: string, message: string, status?: number | null, retry_after_seconds?: number | null, };

export type CommunityNodeIndexingRequest = { base_url: string, scope_kind: IndexScopeKind, 
/**
 * public の target、private capability の親 topic。
 */
topic_id: string, 
/**
 * private の target。public では指定しない。
 */
channel_id?: string | null, 
/**
 * private secret の外部送信を UI で明示確認したことを示す。
 */
confirm_private_channel_secret_disclosure: boolean, };

export type CommunityNodeIndexingRequestError = { code: string, message: string, status?: number | null, retry_after_seconds?: number | null, };

export type IndexScopeKind = "public_topic" | "private_channel";

export type IndexingRequestStatus = "pending" | "approved" | "rejected";

export type AdvisorySubjectKind = "post_id" | "blob_cid";

export type ContentAdvisory = { 
/**
 * 発行 node（署名鍵の x-only 公開鍵 hex = manifest `node_id`）。
 */
issuer_node_id: string, subject_kind: AdvisorySubjectKind, 
/**
 * post id または blob hash。
 */
subject_id: string, category: SafetyCategory, 
/**
 * client 表示語彙（nsfw → `adult`、objectionable → `sensitive`）。
 */
label: string, 
/**
 * classifier confidence（0-100）。
 */
confidence?: number | null, 
/**
 * 対応する risk signal id（appeal の入口）。
 */
signal_id: string, 
/**
 * 常に `classifier_score`（confirmed へ昇格しない）。
 */
basis: Basis, };

export type IndexEntryView = { scope_kind: IndexScopeKind, scope_id: string, object_id: string, author_pubkey: string, text: string, created_at: number, content_advisories: Array<ContentAdvisory>, };

export type IndexQueryResponse = { entries: Array<IndexEntryView>, };

export type CommunityNodeContentAdvisoryLookupRequest = { 
/**
 * 可視の投稿 id(引用元・返信先を含む)。
 */
post_ids: Array<string>, 
/**
 * 可視の添付 blob hash。
 */
blob_hashes: Array<string>, };

export type CommunityNodeContentAdvisoryLookupError = { code: string, message: string, status?: number | null, };

export type CommunityNodeContentAdvisoryNodeResult = { base_url: string, 
/**
 * manifest で確認した発行元(= advisory の `issuer_node_id`)。
 */
node_id?: string | null, advisories: Array<ContentAdvisory>, error?: CommunityNodeContentAdvisoryLookupError | null, };

export type CommunityNodeContentAdvisoryLookupResult = { 
/**
 * 照会対象になった(採用 ON の)node ごとの結果。
 */
nodes: Array<CommunityNodeContentAdvisoryNodeResult>, };

export type CommunityIndexPostResolveInput = { key: string, topic: string, object_id: string, author_pubkey: string, channel_ref: ChannelRef, };

export type CommunityIndexPostActionCapabilitiesView = { open_thread: boolean, reply: boolean, repost: boolean, quote_repost: boolean, react: boolean, copy_link: boolean, bookmark: boolean, withdraw: boolean, };

export type CommunityIndexResolvedPostView = { key: string, post?: PostView | null, capabilities: CommunityIndexPostActionCapabilitiesView, };

export type CommunityIndexPostResolveResponse = { entries: Array<CommunityIndexResolvedPostView>, };

export type SubmitIndexingRequestResponse = { request_id: string, status: IndexingRequestStatus, };

export type CommunityNodeIndexingStatusRequest = { base_url: string, scope_kind?: IndexScopeKind | null, 
/**
 * public の target、private capability の親 topic。`scope_kind` 指定時は必須。
 */
topic_id?: string | null, 
/**
 * private の target。public では指定しない。
 */
channel_id?: string | null, 
/**
 * private の所属証明(channel secret)を外部送信することを UI で明示確認した。
 */
confirm_private_channel_secret_disclosure: boolean, };

export type IndexingRequestView = { request_id: string, scope_kind: IndexScopeKind, target_id: string, status: IndexingRequestStatus, 
/**
 * 申請時刻(unix ms)。
 */
created_at: number, 
/**
 * 承認・却下時刻(unix ms)。審査待ちでは null。
 */
decided_at?: number | null, };

export type IndexingTargetStatus = { scope_kind: IndexScopeKind, scope_id: string, supported: boolean, };

export type IndexingStatusResponse = { 
/**
 * 呼出し主の申請だけ。他利用者の申請は含まない。
 */
requests: Array<IndexingRequestView>, 
/**
 * `scope_kind` / `scope_id` を指定した場合のみ。非公開チャンネルは所属証明が必要。
 */
target?: IndexingTargetStatus | null, };

export type CommunityNodeUserAdvisoryRequest = { base_url: string, target_pubkey: string, };

export type CommunityNodeRelationNeighborsRequest = { base_url: string, limit?: number | null, };

export type CommunityNodeTrustRelationError = { code: string, message: string, status?: number | null, };

export type CommunityNodeReportAppeal = { risk_signal_id: string, };

export type CommunityNodeReportError = { code: string, message: string, status?: number | null, };

export type CommunityNodeTesterFeedbackSubmission = { base_url: string, 
/**
 * やろうとしたこと。
 */
what_attempted: string, 
/**
 * 何が起きたか。
 */
what_happened: string, 
/**
 * 何が変だと思ったか。
 */
what_seemed_wrong: string, };

export type CommunityNodeTesterFeedbackResponse = { 
/**
 * 保存されたレポートの ID。
 */
reference_id?: string | null, };

export type CommunityNodeTesterFeedbackError = { code: string, message: string, status?: number | null, retry_after_seconds?: number | null, };

export type TrustComponentKind = "absolute" | "relative";

export type SafetyCategory = "csam" | "cse" | "grooming" | "nsfw" | "objectionable" | "spam" | "malware" | "phishing" | "provider_test";

export type Severity = "critical" | "high" | "medium" | "low";

export type Basis = "known_hash_match" | "provider_verdict" | "classifier_score" | "local_policy";

export type Visibility = "local" | "subscribed_nodes" | "public";

export type AppealStatus = "none" | "disputed" | "cleared";

export type RiskSignalTarget = "user_pubkey" | "peer_node" | "post_id" | "blob_cid";

export type TrustBasisEntry = { signal_id: string, issuer_node_id: string, target: RiskSignalTarget, target_id: string, component: TrustComponentKind, category: SafetyCategory, severity: Severity, basis: Basis, confidence?: number | null, visibility: Visibility, appeal_status: AppealStatus, expires_at?: string | null, 
/**
 * operator が審査・運用是正で値を確定した時刻（RFC3339、#1058）。`None` は scanner 由来の
 * 未訂正判定。旧 node の応答では欠落する。
 */
operator_adjusted_at?: string | null, raw_contribution: number, decay_factor: number, relation_weight: number, contribution: number, };

export type TrustEvaluationReason = "risk_signals" | "related_users_block_or_mute";

export type TrustEvaluation = { 
/**
 * 合算・表示 policy の parameter から決まる識別子。
 */
policy_version: string, 
/**
 * T に寄与する入力の digest。
 */
trust_version: string, 
/**
 * relation snapshot と対象への観測 revision の組。
 */
relation_version: string, computed_at: string, 
/**
 * クライアントが結果を再利用してよい期限（RFC3339）。
 */
expires_at: string, 
/**
 * node-local な表示 policy による非表示推奨（`trust <= hide_threshold`）。
 */
hide_recommended: boolean, reasons: Array<TrustEvaluationReason>, };

export type CommunityNodeObservationSharingStatus = { base_url: string, 
/**
 * CN が任意文書を公開しているか。取得できなかった場合は false。
 */
offered: boolean, 
/**
 * 公開中の任意文書（有効化ダイアログで提示する）。
 */
policy?: CommunityNodePolicyDocument | null, 
/**
 * 提供中か。
 */
enabled: boolean, 
/**
 * CN の文書が更新され、再同意まで提供を止めているか。
 */
needs_reconsent: boolean, 
/**
 * 保存済み観測の削除要求が未完了か（完了まで提供を再開しない）。
 */
revocation_pending: boolean, 
/**
 * 送信待ちの件数。
 */
pending_count: number, };

export type AuthorTrustGate = { author_pubkey: string, 
/**
 * この機能で投稿を折りたたむか。未評価・例外設定では false。
 */
hidden: boolean, 
/**
 * 判断に使った CN。未評価なら None。
 */
node_base_url?: string | null, 
/**
 * 評価が下がった理由の種類（CN が返す種類のみ。observer も件数も含まない）。
 */
reasons: Array<TrustEvaluationReason>, 
/**
 * 採用した評価の期限（RFC3339）。
 */
expires_at?: string | null, 
/**
 * 利用者が「常に表示する」を設定している著者か。
 */
always_visible: boolean, };

export type AuthorTrustGateRequest = { author_pubkeys: Array<string>, };

export type AuthorTrustGateResult = { gates: Array<AuthorTrustGate>, };

export type SetAuthorTrustDisplayExceptionRequest = { author_pubkey: string, 
/**
 * true にすると、信頼値による折りたたみをこの著者には適用しない。
 */
always_visible: boolean, };

export type EnableCommunityNodeObservationSharingRequest = { base_url: string, policy_version: number, policy_snapshot_revision?: string | null, language: string, 
/**
 * 既存のブロック / ミュートも送るか（既定は送らない）。
 */
include_existing: boolean, };

export type TrustReadView = { target_id: string, absolute: number, relative: number, trust: number, w_abs_applied: number, computed_at: string, basis: Array<TrustBasisEntry>, 
/**
 * 評価の版・期限・表示 policy（#1061）。旧 node の応答では欠落し、クライアントは未評価として扱う。
 */
evaluation?: TrustEvaluation | null, };

export type TrustUserReadResponse = { viewer_pubkey: string, target_id: string, absolute: number, relative: number, trust: number, w_abs_applied: number, computed_at: string, basis: Array<TrustBasisEntry>, 
/**
 * 評価の版・期限・表示 policy（#1061）。旧 node の応答では欠落し、クライアントは未評価として扱う。
 */
evaluation?: TrustEvaluation | null, };

export type ProximityBasisEntry = { feature: string, value: number, weight: number, contribution: number, };

export type Proximity = { score: number, basis: Array<ProximityBasisEntry>, };

export type RelationReadResponse = { viewer_pubkey: string, target_pubkey: string, score: number, basis: Array<ProximityBasisEntry>, };

export type RelationNeighborsResponse = { viewer_pubkey: string, neighbors: Array<string>, };

export type RelationOptoutResponse = { pubkey: string, opted_out: boolean, opted_out_at?: string | null, min_proximity: number, };

export type SubmitCommunityNodeReportRequest = { 
/**
 * 通報先 node の base url。構成済みノードでなければ送信しない(#703)。
 */
node_base_url: string, 
/**
 * node manifest が公開する通報受付 endpoint（絶対 http(s) URL）。
 * `node_base_url` と同一オリジンでなければ送信しない(#703)。
 */
report_endpoint: string, 
/**
 * 通報対象の種別（post / profile / media / search_result / recommendation 等）。
 */
subject_kind: string, 
/**
 * 通報対象の識別子（post id / pubkey / object id 等）。
 */
subject_id: string, 
/**
 * 通報先となった node capability（community_index / moderation / media_cache 等）。
 */
capability: string, 
/**
 * 通報理由カテゴリ。
 */
reason: string, 
/**
 * 任意の補足説明。
 */
details?: string | null, 
/**
 * 任意の通報者連絡先（node が follow-up に使える）。
 */
reporter_contact?: string | null, 
/**
 * リスク判定への異議申し立て。通常の通報では省略する。
 */
appeal?: CommunityNodeReportAppeal | null, };

export type SubmitCommunityNodeReportStatus = "submitted";

export type SubmitCommunityNodeReportResult = { status: SubmitCommunityNodeReportStatus, 
/**
 * node が返した受付参照 ID（任意）。
 */
reference_id?: string | null, 
/**
 * 異議申し立てが受理され、`Disputed` へ移ったリスク判定の識別子。
 */
disputed_risk_signal_id?: string | null, };

export type RuntimeEvent = { "type": "notification_status_changed" } | { "type": "sync_status_changed", sync_status?: SyncStatus | null, community_node_statuses?: Array<CommunityNodeNodeStatus> | null, };

export type CreatePostRequest = { topic: string, content: string, reply_to?: string | null, channel_ref: ChannelRef, attachments: Array<CreateAttachmentRequest>, 
/**
 * #858: 投稿者自己申告のラベル(既知値は `adult` のみ)。
 */
content_labels: Array<string>, };

export type WithdrawalReasonVisibilityRequest = "public" | "private";

export type PostWithdrawalReasonRequest = "author_request" | "correction" | "privacy" | "other";

export type WithdrawPostRequest = { topic: string, object_id: string, channel_ref: ChannelRef, replacement_object_id?: string | null, reason_visibility: WithdrawalReasonVisibilityRequest, reason?: PostWithdrawalReasonRequest | null, };

export type CreateRepostRequest = { topic: string, source_topic: string, source_object_id: string, commentary?: string | null, };

export type CreateAttachmentRequest = { file_name?: string | null, mime: string, byte_size: number, data_base64: string, role?: string | null, };

export type ReactionKeyRequest = { "kind": "emoji", emoji: string, } | { "kind": "custom_asset", asset_id: string, owner_pubkey: string, blob_hash: string, search_key: string, mime: string, bytes: number, width: number, height: number, };

export type ToggleReactionRequest = { target_topic_id: string, target_object_id: string, reaction_key: ReactionKeyRequest, channel_ref?: ChannelRef | null, };

export type CustomReactionCropRect = { x: number, y: number, size: number, };

export type CreateCustomReactionAssetRequest = { upload: CreateAttachmentRequest, crop_rect: CustomReactionCropRect, search_key: string, };

export type BookmarkCustomReactionRequest = { asset_id: string, owner_pubkey: string, blob_hash: string, search_key: string, mime: string, bytes: number, width: number, height: number, };

export type RemoveBookmarkedCustomReactionRequest = { asset_id: string, };

export type BookmarkPostRequest = { topic: string, object_id: string, channel_ref: ChannelRef, };

export type ResolveCommunityIndexPostsRequest = { entries: Array<CommunityIndexPostResolveInput>, };

export type RemoveBookmarkedPostRequest = { object_id: string, };

export type ListRecentReactionsRequest = { limit?: number | null, };

export type ListTimelineRequest = { topic: string, scope: TimelineScope, cursor?: TimelineCursor | null, limit?: number | null, };

export type ListThreadRequest = { topic: string, thread_id: string, cursor?: TimelineCursor | null, limit?: number | null, };

export type ListProfileTimelineRequest = { pubkey: string, cursor?: TimelineCursor | null, limit?: number | null, };

export type ImportPeerTicketRequest = { ticket: string, };

export type UnsubscribeTopicRequest = { topic: string, };

export type SetTopicGossipEnabledRequest = { topic: string, enabled: boolean, };

export type SetChannelGossipEnabledRequest = { topic: string, channel: string, enabled: boolean, };

export type GetBlobPreviewRequest = { hash: string, mime: string, metaverse_kind?: MetaverseAssetKind | null, };

export type GetBlobMediaRequest = { hash: string, mime: string, };

export type AuthorRequest = { pubkey: string, };

export type ListSocialConnectionsRequest = { kind: SocialConnectionKind, };

export type DirectMessageRequest = { pubkey: string, };

export type NotificationIdRequest = { notification_id: string, };

export type ListDirectMessageMessagesRequest = { pubkey: string, cursor?: TimelineCursor | null, limit?: number | null, };

export type SendDirectMessageRequest = { pubkey: string, text?: string | null, reply_to_message_id?: string | null, attachments: Array<CreateAttachmentRequest>, };

export type DeleteDirectMessageMessageRequest = { pubkey: string, message_id: string, };

export type SetMyProfileRequest = { name?: string | null, display_name?: string | null, about?: string | null, picture_upload?: CreateAttachmentRequest | null, clear_picture: boolean, };

export type InitialProfileRequest = { account_id: string, profile: SetMyProfileRequest, };

export type CreateAccountRequest = { account_id: string, operation_id: string, };

export type ListLiveSessionsRequest = { topic: string, scope: TimelineScope, };

export type CreateLiveSessionRequest = { topic: string, channel_ref: ChannelRef, title: string, description: string, };

export type LiveSessionCommandRequest = { topic: string, session_id: string, };

export type ListGameRoomsRequest = { topic: string, scope: TimelineScope, };

export type CreateGameRoomRequest = { topic: string, channel_ref: ChannelRef, title: string, description: string, participants: Array<string>, };

export type CreateMetaverseRoomRequest = { topic: string, channel_ref: ChannelRef, title: string, description: string, max_peers?: number | null, };

export type PublishMetaverseRoomEventRequest = { topic: string, room_id: string, peer_id: string, seq: number, event: MetaverseRoomEventV1, };

export type ListMetaverseRoomEventsRequest = { topic: string, room_id: string, after_envelope_id?: string | null, limit?: number | null, };

export type ImportMetaverseRoomAssetRequest = { topic: string, room_id: string, kind: MetaverseAssetKind, mime_type: string, name?: string | null, data_base64: string, };

export type CreatePrivateChannelRequest = { topic: string, label: string, audience_kind: ChannelAudienceKind, };

export type ExportPrivateChannelInviteRequest = { topic: string, channel_id: string, expires_at?: number | null, };

export type ImportPrivateChannelInviteRequest = { token: string, };

export type ExportChannelAccessTokenRequest = { topic: string, channel_id: string, expires_at?: number | null, };

export type ImportChannelAccessTokenRequest = { token: string, };

export type PreviewChannelAccessTokenRequest = { token: string, };

export type ExportFriendOnlyGrantRequest = { topic: string, channel_id: string, expires_at?: number | null, };

export type ImportFriendOnlyGrantRequest = { token: string, };

export type ExportFriendPlusShareRequest = { topic: string, channel_id: string, expires_at?: number | null, };

export type ImportFriendPlusShareRequest = { token: string, };

export type FreezePrivateChannelRequest = { topic: string, channel_id: string, };

export type RotatePrivateChannelRequest = { topic: string, channel_id: string, };

export type SetPrivateChannelEntryDomeRequest = { topic: string, channel_id: string, entry_dome_instance_id?: string | null, };

export type LeavePrivateChannelRequest = { topic: string, channel_id: string, };

export type ListJoinedPrivateChannelsRequest = { topic: string, };

export type UpdateGameRoomRequest = { topic: string, room_id: string, status: GameRoomStatus, phase_label?: string | null, scores: Array<GameScoreView>, };

export type UpdateMetaverseRoomRequest = { topic: string, room_id: string, status: GameRoomStatus, customization: DomeCustomizationV1, };

export type GetDomeHostingRequest = { spatial_context: SpatialContextV1, instance_id: string, };

export type StartOwnerDomeHostingRequest = { expected_generation?: number | null, spatial_context: SpatialContextV1, instance_id: string, endpoint_id: string, lease_duration_millis: number, };

export type DelegateDomeHostingRequest = { expected_generation?: number | null, spatial_context: SpatialContextV1, instance_id: string, node_id: string, base_url: string, lease_duration_millis: number, };

export type CloseDomeHostingRequest = { expected_generation?: number | null, spatial_context: SpatialContextV1, instance_id: string, };

export type SubmitDomeSessionInputRequest = { expected_generation?: number | null, spatial_context: SpatialContextV1, instance_id: string, sequence: number, input: DomeSessionInputKindV1, };

export type PrepareDomeTransitionRequest = { request: DomeTransitionAdmissionRequestV1, };

export type CommitDomeTransitionRequest = { ticket: DomeTransitionAdmissionTicketV1, position: [number, number, number], rotation: [number, number, number], };

export type AbortDomeTransitionRequest = { ticket: DomeTransitionAdmissionTicketV1, };

export type CommitDomeLayoutRequest = { spatial_context: SpatialContextV1, instance_id: string, operation_id: string, };

export type ResyncDomeSnapshotsRequest = { spatial_context: SpatialContextV1, instance_id: string, after_sequence: number, };

export type MoveDomeRequest = { source_topic: string, move_id: string, source_instance_id: string, target_context: SpatialContextV1, };

export type ListDomeConnectionTopologyRequest = { spatial_context: SpatialContextV1, };

export type CreateDomeConnectionProposalRequest = { proposal_id: string, spatial_context: SpatialContextV1, proposer_instance_id: string, receiver_instance_id: string, proposer_direction: DomeDirection, };

export type AcceptDomeConnectionProposalRequest = { spatial_context: SpatialContextV1, proposal_id: string, };

export type WithdrawDomeConnectionProposalRequest = { spatial_context: SpatialContextV1, proposal_id: string, };

export type RevokeDomeConnectionRequest = { spatial_context: SpatialContextV1, connection_id: string, };

export type SetCommunityNodeConfigNode = { base_url: string, 
/**
 * #1056: content advisory の採用。未指定は保存済みの値を維持し、新規 node は true。
 */
content_advisory_enabled?: boolean | null, };

export type SetCommunityNodeConfigRequest = { nodes: Array<SetCommunityNodeConfigNode>, 
/**
 * #1061: 信頼値の採用順位。未指定は保存済みの順位を維持する。
 */
trust_node_priority?: Array<string> | null, };

export type SetCommunityNodeInviteCodeRequest = { base_url: string, invite_code?: string | null, };

export type CommunityNodeTargetRequest = { base_url: string, };

export type AcceptCommunityNodeConsentsRequest = { base_url: string, documents: Array<CommunityNodeConsentDocumentRef>, language: string, };

export type SetDiscoverySeedsRequest = { seed_entries: Array<string>, };

export type ExportAccountKeyRequest = { passphrase: string, };

export type PreviewAccountKeyImportRequest = { export: string, };

export type ImportAccountKeyRequest = { export: string, passphrase: string, label?: string | null, };

export type SwitchAccountRequest = { account_id: string, };

export type AccountRecord = { id: string, pubkey: string, label?: string | null, created_at: number, last_used_at: number, };

export type AccountDisplay = { id: string, name?: string | null, display_name?: string | null, picture?: string | null, unavailable: boolean, };

export type AccountsSnapshot = { active_account_id: string, accounts: Array<AccountRecord>, };

export type AccountKeyExport = { export: string, public_key: string, };

export type AccountKeyImportPreview = { version: number, kdf: string, public_key: string, already_registered: boolean, };

export type CreateDeviceBackupRequest = { path: string, passphrase: string, frontend_state: { [key in string]: string }, };

export type PreviewDeviceBackupRequest = { path: string, passphrase: string, };

export type RestoreDeviceBackupRequest = { path: string, passphrase: string, replace_existing: boolean, apply_frontend_state: boolean, };

export type DeviceBackupSummary = { path: string, public_key: string, bytes: number, };

export type DeviceBackupPreview = { public_key: string, account_label?: string | null, created_at: number, app_version: string, content_bytes: number, existing_account_id?: string | null, included: Array<string>, requires_reconsent: Array<string>, };

export type DeviceBackupRestoreResult = { account: AccountRecord, frontend_state: { [key in string]: string }, };

export type DeviceBackupPhase = "scanning" | "encrypting" | "decrypting" | "installing";

export type DeviceBackupProgress = { phase: DeviceBackupPhase, completed_bytes: number, total_bytes: number, };

